trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn
    yarn build
  displayName: 'yarn install and build'

- script: |
    yarn test
  displayName: 'test'